### PR TITLE
Fix references to GitHub

### PR DESCRIPTION
**Pull request by maxbeizer**
The "H" in GitHub should be capitalized.

source: I'm staff 😸

### CODE REVIEW

**Comment by maxbeizer** [comment]
I'm going to fix up a few others while I'm at it 😄

**Comment by philipithomas** [comment]
Ok, I'll leave this open until you add the others. Just add a comment when it's ready to merge!

**Comment by maxbeizer** [comment]
@philipithomas I think that should do it. I'm just getting started reading this but it looks interesting 😍

**Comment by philipithomas** [comment]
Thanks @maxbeizer !

**Pull request merged**
